### PR TITLE
Move CID to Secret Object

### PR DESCRIPTION
**Pull request by cmartintlh**
To fulfill the CID portion of #43, this PR moves the `falcon.cid` value to a secret object created by Helm. 

Additionally, this provides a field `existingSecretName` for a user to leverage an existing Kubernetes Secret for the Deployment/Daemonset to point to. This allows users to leverage other secret management solutions to create the secret object and keep the CID out of source control, where values files may be stored.

### CODE REVIEW

**Comment by redhatrises** [comment]
Thanks for opening this PR.

There are a few problems that need to be resolved:

1. falcon.cid needs to remain required. This is intentional and has already tripped up more than a few individuals.
2. Helm charts shouldn't modify objects outside of their control. `existingSecretName` shouldn't be added.
3. The build failures need to be fixed. `oneOf` can't be used.

**Comment by cmartintlh** [comment]
Hi @redhatrises, thanks for your review on this. 

The problem we face at our organization is that we commit our values files to source control (we leverage FluxCD's HelmReleases). Thus, having `falcon.cid` as a required value will expose our Customer ID in Git. The introduction of the `existingSecretName` value would circumvent this issue by allowing the use of a secret created by a tool like [sealed-secrets](https://github.com/bitnami-labs/sealed-secrets) or [external-secrets](https://github.com/external-secrets/kubernetes-external-secrets), and then reference the existing secret object in the release. Since we're only referencing an existing secret name for use with the Daemonset/Deployment, the chart would not be modifying the object. 

I'm happy to modify this PR to omit the `existingSecretName` and keep `falcon.cid` as a required value, but curious on your thoughts in the above use case.

**Comment by redhatrises** [comment]
The helm chart will definitely be updated in the next month or so to deploy a CRD with the falcon-operator vs what the helm chart does today. This will allow the sensor to be installed with API credentials outside of the having to specify the CID... which you can still do. However, most of the configuration will now be done via CRD.

**Comment by cmartintlh** [comment]
Thanks for the additional insight @redhatrises. Sounds like it'll be best to wait for that update. Should I close this PR?

**Comment by redhatrises** [comment]
If you want... or keep it open as a reminder as well as for others to use... whatever you prefer.

**Comment by cmartintlh** [comment]
I'll keep it open for now. Thanks!

**Comment by gazal-k** [comment]
The new CRDs mentioned here: https://github.com/CrowdStrike/falcon-operator also don't seem to have any mechanism to set the `client_id` & `client_secret` from a secret.

**Comment by cookandy** [comment]
+1 for allowing us the ability to use existing secrets for customer ID, provisioning tokens, and API tokens.

**Comment by cmartintlh** [comment]
> For anyone experiencing this particular issue, you can use [valuesFrom](https://fluxcd.io/flux/components/helm/helmreleases/#values-overrides) to merge values from a secret into your HelmRelease.

This is a good solution and something I overlooked 😃

**Comment by redhatrises** [comment]
Closing as we won't be supporting secret injection.

**Pull request closed without merging**
