### PR TITLE
fix: docs. fix imagepullpolicy

### PR DESCRIPTION
**Pull request by domdepasquale**
I'm fairly certain message_log is an unusable option.

### CODE REVIEW

**Comment by domdepasquale** [comment]
I'll bump the chart version once we verify this fix is necessary

**Comment by redhatrises** [comment]
@domdepasquale should we verify that it exists for all initContainers?

**Review by redhatrises — CHANGES_REQUESTED** [review]
@domdepasquale pretty sure message log is an option in the linux sensor

**Comment by domdepasquale** [comment]
> @domdepasquale pretty sure message log is an option in the linux sensor

I removed the offending commit. thanks @redhatrises

**Review by redhatrises — APPROVED** [review]

**Pull request merged**
