### PR TITLE
:sparkles: (feat): Addded ability to reference existing pullsecret

### PR DESCRIPTION
**Pull request by KrisJohnstone**
Added the ability to reference pullsecrets via linking secret to the service account.

### CODE REVIEW

**Comment by redhatrises** [comment]
Hello,

Can you provide some additional context on why this method is needed?

**Comment by KrisJohnstone** [comment]
> Hello,
> 
> Can you provide some additional context on why this method is needed?

When using GitOps to deploy this chart, the only provision provided for pullsecrets at present is by committing the pullsecret to git which is bad juju.

**Comment by redhatrises** [comment]
> > Hello,
> > Can you provide some additional context on why this method is needed?
> 
> When using GitOps to deploy this chart, the only provision provided for pullsecrets at present is by committing the pullsecret to git which is bad juju.

Does setting `node.image.pullSecrets` to the existing pull secret not work?

**Comment by KrisJohnstone** [comment]
> > > Hello,
> > > Can you provide some additional context on why this method is needed?
> > 
> > 
> > When using GitOps to deploy this chart, the only provision provided for pullsecrets at present is by committing the pullsecret to git which is bad juju.
> 
> Does setting `node.image.pullSecrets` to the existing pull secret not work?

That requires me to commit a pull secret to git unencrypted.

**Comment by redhatrises** [comment]
> That requires me to commit a pull secret to git unencrypted.

This is incorrect. Setting `node.image.pullSecrets` to the name of your custom secret is what you are wanting and attempting to do, e.g.:

```
--set node.image.pullSecrets=mysecretname
```
Please use this to not store your secret in git unencrypted.

**Comment by KrisJohnstone** [comment]
Apologies was in a rush and must have been confused with the line underneath then which talks about base64.

**Pull request closed without merging**
