### PR TITLE
Add basic value schema for input validation

### PR DESCRIPTION
**Pull request by redhatrises**

### CODE REVIEW

**Comment by redhatrises** [comment]
Looks like gh actions is having problems... please don't merge yet.

**Comment by redhatrises** [comment]
There is a bug in helm that prevents `helm lint` from validating correctly with set values with `values.schema.json`. We will have to wait until helm 3.6 is release before we can use this.

**Comment by redhatrises** [comment]
This is ready for review.

**Review by isimluk — APPROVED** [review]
👍

**Pull request merged**
